### ISSUE TITLE
What WROVER_KIT_LCD lib

### ISSUE THREAD

**Issue by Kabron287** [tobozo/ESP32-BLECollector#1]
What WROVER_KIT_LCD lib you used?
error: 'class WROVER_KIT_LCD' has no member named 'setupScrollArea'
error: no matching function for call to 'WROVER_KIT_LCD::getTextBounds(String&, int&, int&, int16_t*, int16_t*, uint16_t*, uint16_t*)'

also
src\UI.h:177:85: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]

**Comment by tobozo** [comment]
> error: 'class WROVER_KIT_LCD' has no member named 'setupScrollArea'

You need to [patch the WROVER library](https://github.com/espressif/WROVER_KIT_LCD/pull/3/files) as specified in the [Settings.h](https://github.com/tobozo/ESP32-BLECollector/blob/master/Settings.h#L72) file, I'll update the Readme to make this more clear.

Also make sure you're using a [fresh version of Adafruit_GFX](https://github.com/adafruit/Adafruit-GFX-Library) (mine is 1.3.2) to make the invalid conversion error go away.

**Comment by tobozo** [comment]
I'll post an update soon, just spent some time replacing some `String()` by `const char*` to slow down the memory leaks.

**Comment by Kabron287** [comment]
Really, ESP32 has unprecedented sensitivity. It finds twice more devices then my Samsung A5

**Comment by tobozo** [comment]
[There's a catch](https://github.com/tobozo/ESP32-BLECollector/blob/master/BLE.h#L90)

**Comment by tobozo** [comment]
BTW I haven't tried this yet on Odroid or M5, not sure it'll even work since there may be different scroll support on the respective TFT.

I don't see the point anyway since the viewing angle is a problem on both M5 and Odroid when used with the scroll settings of this app.

However, if you tried it I'm still interested to know how it went ^_^

**Comment by Kabron287** [comment]
I'm going to try

**Comment by orangedrink** [comment]
Any more information coming on how to patch that library in? Is that still part of settings.h? Thanks!!

**Comment by tobozo** [comment]
hey @orangedrink thanks for your feedback

This is the state of the library for the esp32-wrover-kit LCD, the PR is still being discussed but it works:

https://github.com/espressif/WROVER_KIT_LCD/pull/4/files

**Comment by orangedrink** [comment]
Thanks @tobozo! That got me on to the next problem. Stay tuned for more pleas for help. Ha!

This looks like a really cool piece of software! thanks for all of your work on this. 🥇

**Comment by tobozo** [comment]
WROVER_KIT_LCD has been removed from the project, the display is now handled by the ESP32-Chimera-Core (see readme for links).

Closing this issue as not relevant any more.
Feel free to reopen or add updates :)
