### ISSUE TITLE
WROVER SD Card

### ISSUE THREAD

**Issue by czuvich** [tobozo/ESP32-BLECollector#17]
Did you use the SD Card on the WROVER Kit?  If so, how did you get both the LCD and SD Card to work properly?  I desoldered R167 and I'm able to get the LCD to display with a card inserted; however, the SD fails to initialize if I initialize the LCD first (and vice versa).

My code is straightforward:

```C++
SPI.begin(14, 2, 15, 13);
  if (!SD.begin(13)) {
   ESP_LOGE(LOG_TAG, "<< Failed. LocalStorage is not available.");
}
```

I saw in your code you were using MMC.  Maybe that's what I need to do?  Thanks!

**Comment by tobozo** [comment]
What's your wrover-kit version ? mine is 4.1 and it works out of the box with SD_MMC.h, doesn't work with SD.h.

However, I also have the wrover-kit v3 and it's the other way around, it won't work with SD_MMC.h, only with SD.h. Actually I never could get SD + TFT to work simultaneously on the wrover-kit v3, but I know it's possible by doing some init voodoo like m5stack or odroid do, I know @kabron287 was planning to play with those different profiles but haven't heard since (ping?).

And there's another catch : don't create FAT32 partitions bigger than 32GB otherwise it won't mount.

**Comment by czuvich** [comment]
I'm using 4.1.  I actually just tried using native code in Arduino (using sdmmc_host_t host = SDSPI_HOST_DEFAULT()...)  and mounting worked at least, and I got it displaying something in the LCD.  When you say simultaneously, do you mean reading from an SD Card while refreshing the UI in a separate task (on a different core)?

I saw your video, and I assume you're reading the SD card at some point right?  I'll try the SD_MMC example straight from the examples repository.  I may end up simply extending my own FS specifically for the WROVER by just tweaking the SD_MMC library a bit.

**Comment by tobozo** [comment]
yup simultaneous use of SD + TFT *drivers* works natively by using SD_MMC.h and [this display driver](https://github.com/espressif/WROVER_KIT_LCD).

Although I'm using a mux semaphore to isolate display writes and I only remember having crashes related to concurrent display writes, I can't tell if *core0 doing a SD.read() while core1 doing a tft.write()* is possible.

btw baking your own filesystem reminds me of [FFAT](https://github.com/espressif/arduino-esp32/tree/master/libraries/FFat), not SD related but still good as model for custom implementation.

**Comment by czuvich** [comment]
Got it working!  I basically took the SD_MMC.cpp file and modified specifically to the WROVER.  I am able to read/write SD and update the LCD at the same time.  For whatever reason, I couldn't get the SD_MMC example working directly.

**Comment by tobozo** [comment]
what board did you select in the Arduino IDE menu ?

I'm using "Wrover module" with the esp32-sdk 1.0.1 from the boards manager, and I don't remember having to alter the SD_MMC driver to get this working, I didn't even specify pin numbers.

Also there's another catch, psram uses SPI, and I remember having many crashes before figuring out this was interferring, hope this saves you some hard time :-)

**Comment by czuvich** [comment]
I'm using the WROVER Module with 1.0.1.  I thought I had it working, but I'm getting a bus busy re-init message after I read some files from the SD card.  I wonder if I'll have the same problem with an external SD reader (not using the HSPI pins).

**Comment by tobozo** [comment]
there may be a preferred order, I found stability when doing tft.begin() before SD_MMC.begin()

**Comment by czuvich** [comment]
Did you desolder the R167 resistor on your WROVER kit?

**Comment by tobozo** [comment]
nope, but I know it was required in certain conditions on older wroker-kit models

**Comment by czuvich** [comment]
I finally figured it out.  I had to use the SD_MMC.h and change my pin for my RTC.  I used your pinouts (26,27), and I stopped getting the the bus busy error.  Great work on sifting through this stuff.

**Comment by tobozo** [comment]
and if you need an extra serial (e.g. for a gps module) you can also use pins 39/35 as RX/TX
