### ISSUE TITLE
Preferences.h is missing

### ISSUE THREAD

**Issue by thearduinoguy** [tobozo/ESP32-BLECollector#20]
Preferences.h is missing

**Comment by tobozo** [comment]
Using library Preferences at version 1.0 in folder: ~/.arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/Preferences 

not using esp32 core or damaged installation ?

**Comment by tobozo** [comment]
closing this as probably out of scope (the app is for ESP32, won't work with ESP8266), feel free to reopen if necessary
