### ISSUE TITLE
'RGBColor' has not been declared

### ISSUE THREAD

**Issue by 0x77dev** [tobozo/ESP32-BLECollector#29]
```cpp
void setupScrollArea(uint16_t TFA, uint16_t BFA, RGBColor colorstart, RGBColor colorend, bool clear = false) {
```
line 73 in ScrollPanel.h | ScrollPanel.h:73

M5Stack Core, Arduino IDE 1.8.11, Latest Libraries

**Comment by tobozo** [comment]
Thanks for reporting this.

Actually the BLECollector does not use the M5Stack library. 
It uses the [ESP32-Chimera-Core](https://github.com/tobozo/ESP32-Chimera-Core), which you can get it from the Arduino Library manager.

Once ESP32-Chimera-Core is installed, you should choose how you will use it.

  - Choice 1:  remove the existing M5Stack core library and ESP32-Chimera-Core will act as a substitute for any `#include <M5Stack.h>`

  - Choice 2:  keep the existing M5Stack core library but replace all instances of `#include <M5Stack.h>` by `#include <ESP32-Chimera-Core.h>` in the BLECollector code

**Comment by 0x77dev** [comment]
nothing has worked for me.

**Comment by tobozo** [comment]
let's discuss this on the other thread #30, closing this issue for more clarity
