### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by simme** [tobozo/ESP32-BLECollector#39]
Hey!

Just stumbled upon this impressive project! I've been looking around for a way of sniffing BLE packets to reverse engineer the communications of some electronics. Being very new at this "hardware stuff" I'm just struggling a bit to understand if this project could achieve this? Basically I want to sniff traffic and get it into Wireshark somehow. I've got no problem with the code itself, just new to this particular area. So trying to figure out the right end to start in 😅 

Thanks!

Oh, and sorry for making an issue here. Didn't manage to explain myself within a tweet :P

**Comment by tobozo** [comment]
hey @simme thanks for your feedback

The ESP32 is very limited in terms of BLE sniffing, so this app is just a BLE scanner with some gfx.

Using Nordic hardware (e.g. nRF52840) is probably a better choice for WireShark.

**Comment by simme** [comment]
Gotcha!
Thank you for taking the time to answer! :)
