### ISSUE TITLE
M5Stack-fire Compile Error

### ISSUE THREAD

**Issue by LuckyFishGeek** [tobozo/ESP32-BLECollector#45]
ESP32-Chimera-Core  :  1.4.6
ESP32 Development Board  :  2.0.3
device: M5Stack-fire

```log
error log: `Arduino:1.8.19 (Windows 10), Development Board："M5Stack-FIRE, Enabled, Default (2 x 6.5 MB app, 3.6 MB SPIFFS), 921600, Warn"

In file included from C:\Users\Administrator\Documents\Arduino\libraries\ESP32-Chimera-Core\src/ESP32-Chimera-Core-Config.h:1,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\Display.h:1,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\Settings.h:199,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\ESP32-BLECollector.ino:50:

C:\Users\Administrator\Documents\Arduino\libraries\ESP32-Chimera-Core\src/Config.h:55:21: note: #pragma message: ESP32 Arduino 2.0.3 (0x142fceb8) detected

     #pragma message "ESP32 Arduino 2.0.3 (0x142fceb8) detected"

                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\Settings.h:265,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\ESP32-BLECollector.ino:50:

C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\UI.h: In static member function 'static void UIUtils::screenShot()':

UI.h:430:21: error: request for member 'snap' in 'M5.ChimeraCore::ECCKernel::ScreenShot', which is of pointer type 'ScreenShotService*' (maybe you meant to use '->' ?)

       M5.ScreenShot.snap("BLECollector", false); // filename prefix, show image after capture

                     ^~~~

In file included from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\Settings.h:268,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\ESP32-BLECollector.ino:50:

C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\BLE.h: In static member function 'static void BLEScanUtils::screenShotTask(void*)':

BLE.h:904:23: error: request for member 'init' in 'M5.ChimeraCore::ECCKernel::ScreenShot', which is of pointer type 'ScreenShotService*' (maybe you meant to use '->' ?)

         M5.ScreenShot.init( &M5.Lcd, BLE_FS );

                       ^~~~

BLE.h:905:27: error: request for member 'begin' in 'M5.ChimeraCore::ECCKernel::ScreenShot', which is of pointer type 'ScreenShotService*' (maybe you meant to use '->' ?)

         if( M5.ScreenShot.begin() ) {

                           ^~~~~

C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\BLE.h: In static member function 'static void BLEScanUtils::scanInit()':

BLE.h:1200:17: error: 'class NimBLEScan' has no member named 'setAdvertisedDeviceCallbacks'

       pBLEScan->setAdvertisedDeviceCallbacks( FoundDeviceCallback );

                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

exit status 1

request for member 'snap' in 'M5.ChimeraCore::ECCKernel::ScreenShot', which is of pointer type 'ScreenShotService*' (maybe you meant to use '->' ?)

```

**Comment by tobozo** [comment]
hey thanks for the feedback, 

Looks like the BLECollector needs to catch up with the new versions of the core and libraries :wink: 
It may take some time tough as some parts of the app will need a full rewrite.

Meanwhile you can try those workarounds:

M5.ScreenShot errors
-----------------------------
Either replace any instance of `M5.ScreenShot.` by a `M5.ScreenShot.->` as suggested by the error message, or downgrade the version of Chimera-Core until it does not complain.

I'd suggest the former as there was a significant gain in memory/flash space when the ScreenShot service was moved to pointers.


Nimble error:
-------------------
Same temporary solution, downgrade the version in your library manager until it stops complaining.

**Comment by LuckyFishGeek** [comment]
> hey thanks for the feedback,
> 
> Looks like the BLECollector needs to catch up with the new versions of the core and libraries 😉 It may take some time tough as some parts of the app will need a full rewrite.
> 
> Meanwhile you can try those workarounds:
> 
> ## M5.ScreenShot errors
> Either replace any instance of `M5.ScreenShot.` by a `M5.ScreenShot.->` as suggested by the error message, or downgrade the version of Chimera-Core until it does not complain.
> 
> I'd suggest the former as there was a significant gain in memory/flash space when the ScreenShot service was moved to pointers.
> 
> ## Nimble error:
> Same temporary solution, downgrade the version in your library manager until it stops complaining.

![Snipaste_2022-10-26_11-35-21](https://user-images.githubusercontent.com/29472751/197928665-340ce275-536c-4757-bcb3-dca3f1db94fb.png)
Modified like this?

**Comment by tobozo** [comment]
only `->` sorry about the typo 

![image](https://user-images.githubusercontent.com/1893754/197953582-f80b97dd-45dd-4b35-adba-0dd96c7bfbc1.png)

**Comment by tobozo** [comment]
there are other errors after that, I'll push an update today but it'll be based on espressif package 2.0.5

**Comment by tobozo** [comment]
I've pushed an update on the master, tested on Arduino and Platformio with my old M5Fire, it's been running for half an hour without a glitch.

**Comment by LuckyFishGeek** [comment]
new error   :  'class NimBLEScan' has no member named 'setAdvertisedDeviceCallbacks'

Compiler Environment:  

ESP32-Chimera-Core 1.4.6
ESP32 Development Board : 2.0.5

log：

Arduino:1.8.19 (Windows 10), development board："M5Stack-FIRE, Enabled, Default (2 x 6.5 MB app, 3.6 MB SPIFFS), 921600, None, Disabled"

In file included from C:\Users\Administrator\Documents\Arduino\libraries\ESP32-Chimera-Core\src/ESP32-Chimera-Core-Config.h:1,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\Display.h:1,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\Settings.h:199,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\ESP32-BLECollector.ino:50:

C:\Users\Administrator\Documents\Arduino\libraries\ESP32-Chimera-Core\src/Config.h:68:21: note: #pragma message: ESP32 Arduino 2.0.5 (0x2d6ca351) detected

     #pragma message "ESP32 Arduino 2.0.5 (0x2d6ca351) detected"

                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\Settings.h:268,

                 from C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\ESP32-BLECollector.ino:50:

C:\Users\Administrator\Desktop\ESP32-BLECollector-master\ESP32-BLECollector\BLE.h: In static member function 'static void BLEScanUtils::scanInit()':

BLE.h:1201:17: error: 'class NimBLEScan' has no member named 'setAdvertisedDeviceCallbacks'

       pBLEScan->setAdvertisedDeviceCallbacks( FoundDeviceCallback );

                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

exit status 1

'class NimBLEScan' has no member named 'setAdvertisedDeviceCallbacks'

**Comment by tobozo** [comment]
update your Nimble-Arduino library to the latest release

**Comment by LuckyFishGeek** [comment]
ok  i try it
thanks

**Comment by LuckyFishGeek** [comment]
Compilation is complete, but nothing is displayed on the screen after install firmware

![Snipaste_2022-10-26_22-22-09](https://user-images.githubusercontent.com/29472751/198052144-74330840-4117-41ff-aedb-54f74cacab4f.png)

I use Visual Studio Code to install the firmware
![Snipaste_2022-10-26_22-23-09](https://user-images.githubusercontent.com/29472751/198052692-cd45c22e-310e-417d-8b4f-7b4df617a44a.png)

It's already night here. Thank you for your help. Go to bed earlier. Good night.

**Comment by tobozo** [comment]
just update all your libraries, this means LovyanGFX too

**Comment by LuckyFishGeek** [comment]
It may not be the libraries, I checked the ones already installed and they are all the latest versions
![Snipaste_2022-10-27_08-08-19](https://user-images.githubusercontent.com/29472751/198161818-0229f43c-5171-4642-87fb-aa2a4407b5b1.png)
![Snipaste_2022-10-27_08-08-47](https://user-images.githubusercontent.com/29472751/198161821-7f5c2b7d-d8a3-4791-8289-6e78fbd8943c.png)
![Snipaste_2022-10-27_08-09-11](https://user-images.githubusercontent.com/29472751/198161822-a0ee7401-bb1a-4fee-a5bd-7c733ca6015e.png)
![Snipaste_2022-10-27_08-07-55](https://user-images.githubusercontent.com/29472751/198161828-40cd58bd-250e-4fda-97a6-570505ae972c.png)

**Comment by tobozo** [comment]
Those are screenshots from Arduino IDE, but you spoke about Visual Studio?

The NimbleScan error message is very strange, can you check you have only one installtion of Nimble-Arduino ? 

It looks like you have an old one too :-)

**Comment by LuckyFishGeek** [comment]
The last question: what are the functions of the three buttons? I don't seem to see it in the readme documentation

**Comment by tobozo** [comment]
Brightness +/- and toggle the vendor filter (hides BLE addresses with unknown vendor)

```cpp
        if( M5.BtnA.wasPressed() ) {
          UI.brightness -= UI.brightnessIncrement;
          setBrightnessCB();
        }
        if( M5.BtnB.wasPressed() ) {
          UI.brightness += UI.brightnessIncrement;
          setBrightnessCB();
        }
        if( M5.BtnC.wasPressed() ) {
          toggleFilterCB();
        }
```
